name: "spanorm"
namespace: "methods_normalization"
version: "build_main"
argument_groups:
- name: "Arguments"
  arguments:
  - type: "file"
    name: "--input_spatial_aggregated_counts"
    label: "Aggregated Counts"
    summary: "Unprocessed raw counts after aggregation of transcripts to cells"
    description: "This file contains the raw counts after aggregating transcripts\
      \ to cells.\n"
    info:
      format:
        type: "h5ad"
        layers:
        - type: "integer"
          name: "counts"
          description: "Raw aggregated counts"
          required: true
        obs:
        - type: "string"
          name: "cell_id"
          description: "Unique identifier for the cell (from assignment step)"
          required: true
        - type: "string"
          name: "centroid_x"
          description: "X coordinate of the cell"
          required: true
        - type: "string"
          name: "centroid_y"
          description: "Y coordinate of the cell"
          required: true
        - type: "string"
          name: "centroid_z"
          description: "Z coordinate of the cell"
          required: false
        - type: "string"
          name: "n_counts"
          description: "Number of counts in the cell"
          required: true
        - type: "string"
          name: "n_genes"
          description: "Number of genes in the cell"
          required: true
        var:
        - type: "string"
          name: "gene_name"
          description: "Name of the gene"
          required: true
        - type: "string"
          name: "n_counts"
          description: "Number of counts of the gene"
          required: true
        - type: "string"
          name: "n_cells"
          description: "Number of cells expressing the gene"
          required: true
    example:
    - "resources_test/task_ist_preprocessing/mouse_brain_combined/spatial_aggregated_counts.h5ad"
    must_exist: true
    create_parent: true
    required: true
    direction: "input"
    multiple: false
    multiple_sep: ";"
  - type: "file"
    name: "--input_cell_volumes"
    label: "Cell Volumes"
    summary: "An obs column of cell volumes calculated from spatial transcriptomics\
      \ data."
    description: "An obs column of cell volumes calculated from spatial transcriptomics\
      \ data.\n"
    info:
      format:
        type: "h5ad"
        obs:
        - type: "string"
          name: "volume"
          description: "The volume of the cell."
          required: true
    example:
    - "resources_test/task_ist_preprocessing/mouse_brain_combined/cell_volumes.h5ad"
    must_exist: true
    create_parent: true
    required: false
    direction: "input"
    multiple: false
    multiple_sep: ";"
  - type: "file"
    name: "--output"
    label: "Spatial Normalized"
    summary: "Normalized counts"
    description: "This file contains the normalized counts of the spatial transcriptomics\
      \ data.\n"
    info:
      format:
        type: "h5ad"
        layers:
        - type: "integer"
          name: "counts"
          description: "Raw aggregated counts"
          required: true
        - type: "integer"
          name: "normalized"
          description: "Normalized expression values"
          required: true
        obs:
        - type: "string"
          name: "cell_id"
          description: "Unique identifier for the cell (from assignment step)"
          required: true
        - type: "string"
          name: "centroid_x"
          description: "X coordinate of the cell"
          required: true
        - type: "string"
          name: "centroid_y"
          description: "Y coordinate of the cell"
          required: true
        - type: "string"
          name: "centroid_z"
          description: "Z coordinate of the cell"
          required: false
        - type: "string"
          name: "n_counts"
          description: "Number of counts in the cell"
          required: true
        - type: "string"
          name: "n_genes"
          description: "Number of genes in the cell"
          required: true
        var:
        - type: "string"
          name: "gene_name"
          description: "Name of the gene"
          required: true
        - type: "string"
          name: "n_counts"
          description: "Number of counts of the gene"
          required: true
        - type: "string"
          name: "n_cells"
          description: "Number of cells expressing the gene"
          required: true
    example:
    - "resources_test/task_ist_preprocessing/mouse_brain_combined/spatial_normalized_counts.h5ad"
    must_exist: true
    create_parent: true
    required: true
    direction: "output"
    multiple: false
    multiple_sep: ";"
resources:
- type: "r_script"
  path: "script.R"
  is_executable: true
label: "SpaNorm normalization"
summary: "Spatially-aware normalisation for spatial transcriptomics data"
description: "Spatially-aware normalisation for spatial transcriptomics data"
test_resources:
- type: "file"
  path: "resources_test/task_ist_preprocessing/mouse_brain_combined"
  dest: "resources_test/task_ist_preprocessing/mouse_brain_combined"
- type: "python_script"
  path: "run_and_check_output.py"
  is_executable: true
- type: "python_script"
  path: "check_config.py"
  is_executable: true
info:
  type: "method"
  subtype: "method_normalization"
  type_info:
    label: "Normalization"
    summary: "Normalizing spatial transcriptomics data"
    description: "A normalization method normalizes spatial transcriptomics data to\
      \ account for technical variations and enable comparisons between samples."
status: "enabled"
scope:
  image: "public"
  target: "public"
repositories:
- type: "github"
  name: "openproblems"
  repo: "openproblems-bio/openproblems"
  tag: "build/main"
- type: "github"
  name: "datasets"
  repo: "openproblems-bio/datasets"
  tag: "build/main"
license: "MIT"
references:
  doi:
  - "10.1101/2024.05.31.596908"
links:
  repository: "https://github.com/bhuvad/SpaNorm/tree/master"
  docker_registry: "ghcr.io"
  documentation: "https://github.com/openproblems-bio/task_ist_preprocessing"
runners:
- type: "executable"
  id: "executable"
  docker_setup_strategy: "ifneedbepullelsecachedbuild"
- type: "nextflow"
  id: "nextflow"
  directives:
    label:
    - "veryhightime"
    - "midcpu"
    - "highmem"
    tag: "$id"
  auto:
    simplifyInput: true
    simplifyOutput: false
    transcript: false
    publish: false
  config:
    labels:
      lowmem: "memory = 20.Gb"
      midmem: "memory = 50.Gb"
      highmem: "memory = 100.Gb"
      lowcpu: "cpus = 5"
      midcpu: "cpus = 15"
      highcpu: "cpus = 30"
      lowtime: "time = 1.h"
      midtime: "time = 4.h"
      hightime: "time = 8.h"
      veryhightime: "time = 24.h"
  debug: false
  container: "docker"
engines:
- type: "docker"
  id: "docker"
  image: "openproblems/base_r:1"
  namespace_separator: "/"
  setup:
  - type: "r"
    bioc:
    - "SpaNorm"
    - "anndataR"
    - "rhdf5"
    bioc_force_install: false
    warnings_as_errors: true
  - type: "docker"
    run:
    - "Rscript -e \"BiocManager::install('SingleCellExperiment', type = 'source',\
      \ force = TRUE, ask = FALSE)\"\n"
  entrypoint: []
  cmd: null
- type: "native"
  id: "native"
build_info:
  config: "src/methods_normalization/spanorm/config.vsh.yaml"
  runner: "executable"
  engine: "docker|native"
  output: "target/executable/methods_normalization/spanorm"
  executable: "target/executable/methods_normalization/spanorm/spanorm"
  viash_version: "0.9.4"
  git_commit: "93c2914a1bff5805823036241f2a452416b082e6"
  git_remote: "https://github.com/openproblems-bio/task_ist_preprocessing"
package_config:
  name: "task_ist_preprocessing"
  version: "build_main"
  label: "iST Preprocessing"
  summary: "Benchmarking approaches for preprocessing imaging-based spatial transcriptomics"
  description: "Provide a clear and concise description of your task, detailing the\
    \ specific problem it aims\nto solve. Outline the input data types, the expected\
    \ output, and any assumptions or constraints.\nBe sure to explain any terminology\
    \ or concepts that are essential for understanding the task.\n\nExplain the motivation\
    \ behind your proposed task. Describe the biological or computational\nproblem\
    \ you aim to address and why it's important. Discuss the current state of research\
    \ in\nthis area and any gaps or challenges that your task could help address.\
    \ This section\nshould convince readers of the significance and relevance of your\
    \ task.\n"
  info:
    image: "The name of the image file to use for the component on the website."
    test_resources:
    - type: "s3"
      path: "s3://openproblems-data/resources_test/common/2023_10x_mouse_brain_xenium_rep1/"
      dest: "resources_test/common/2023_10x_mouse_brain_xenium_rep1/"
    - type: "s3"
      path: "s3://openproblems-data/resources_test/common/2023_yao_mouse_brain_scrnaseq_10xv2/"
      dest: "resources_test/common/2023_yao_mouse_brain_scrnaseq_10xv2/"
    - type: "s3"
      path: "s3://openproblems-data/resources_test/task_ist_preprocessing/"
      dest: "resources_test/task_ist_preprocessing"
  repositories:
  - type: "github"
    name: "openproblems"
    repo: "openproblems-bio/openproblems"
    tag: "build/main"
  - type: "github"
    name: "datasets"
    repo: "openproblems-bio/datasets"
    tag: "build/main"
  viash_version: "0.9.4"
  source: "src"
  target: "target"
  config_mods:
  - ".runners[.type == \"nextflow\"].config.labels := { lowmem : \"memory = 20.Gb\"\
    , midmem : \"memory = 50.Gb\", highmem : \"memory = 100.Gb\", lowcpu : \"cpus\
    \ = 5\", midcpu : \"cpus = 15\", highcpu : \"cpus = 30\", lowtime : \"time = 1.h\"\
    , midtime : \"time = 4.h\", hightime : \"time = 8.h\", veryhightime : \"time =\
    \ 24.h\" }\n"
  authors:
  - name: "Louis KÃ¼mmerle"
    roles:
    - "author"
    - "maintainer"
    info:
      github: "LouisK92"
      orcid: "0000-0002-9193-1243"
  - name: "Malte D. Luecken"
    roles:
    - "author"
    info:
      github: "LuckyMD"
      orcid: "0000-0001-7464-7921"
  - name: "Daniel Strobl"
    roles:
    - "author"
    info:
      github: "danielStrobl"
      orcid: "0000-0002-5516-7057"
  - name: "Robrecht Cannoodt"
    roles:
    - "author"
    info:
      github: "rcannood"
      orcid: "0000-0003-3641-729X"
  keywords:
  - "spatial transcriptomics"
  - "imaging-based spatial transcriptomics"
  - "preprocessing"
  license: "MIT"
  organization: "openproblems-bio"
  links:
    repository: "https://github.com/openproblems-bio/task_ist_preprocessing"
    docker_registry: "ghcr.io"
    issue_tracker: "https://github.com/openproblems-bio/task_ist_preprocessing/issues"
