name: normalise_by_volume
namespace: normalisation_methods

arguments:
  - name: --input
    required: true
    direction: input
    __merge__: /src/api/file_spatial_raw_counts.yaml
  - name: --input_volume
    type: file
    description: H5ad with an obs column of cell volumes calculated from spatial transcriptomics data.
    required: true
    __merge__: /src/api/file_cell_volumes.yaml
  - name: --output
    required: true
    direction: output
    __merge__: /src/api/file_spatial_norm_counts.yaml

resources:
  - type: python_script
    path: script.py

engines:
  - type: docker
    image: openproblems/base_python:1.0.0
    setup:
      - type: python
        github: [theislab/txsim@dev]
  - type: native

runners:
  - type: executable
  - type: nextflow
