name: process_vizgen_merscope
namespace: datasets/workflows

argument_groups:
  - name: Inputs
    arguments:
      - type: string
        name: --gcloud_bucket
        default: "vz-ffpe-showcase"
        description: "Google cloud bucket name"
      - type: string
        name: --dataset_bucket_name
        default: "HumanBreastCancerPatient1"
        description: "The name of the dataset base directory in the vizgen google cloud bucket"
      - type: string
        name: --segmentation_id
        default: ["cell"]
        description: The segmentation identifier
        multiple: true
  - name: Metadata
    arguments:
      #- type: string
      #  name: --id
      #  description: "A unique identifier for the dataset"
      #  required: true
      - name: --dataset_name
        type: string
        description: Nicely formatted name.
        required: true
      - type: string
        name: --dataset_url
        description: Link to the original source of the dataset.
        required: false
      - name: --dataset_reference
        type: string
        description: Bibtex reference of the paper in which the dataset was published.
        required: false
      - name: --dataset_summary
        type: string
        description: Short description of the dataset.
        required: true
      - name: --dataset_description
        type: string
        description: Long description of the dataset.
        required: true
      - name: --dataset_organism
        type: string
        description: The organism of the sample in the dataset.
        required: false
  - name: Crop region
    description: If provided, the region will be cropped to the specified coordinates.
    arguments:
      - type: integer
        name: --crop_region_min_x
        required: false
        description: The minimum x coordinate of the region to crop.
      - type: integer
        name: --crop_region_max_x
        required: false
        description: The maximum x coordinate of the region to crop.
      - type: integer
        name: --crop_region_min_y
        required: false
        description: The minimum y coordinate of the region to crop.
      - type: integer
        name: --crop_region_max_y
        required: false
        description: The maximum y coordinate of the region to crop.
  - name: Outputs
    arguments:
    - name: "--output_dataset"
      __merge__: /src/api/file_common_ist.yaml
      direction: output
      required: true
      default: "$id/dataset.zarr"

resources:
  - type: nextflow_script
    path: main.nf
    entrypoint: run_wf
  - path: /common/nextflow_helpers/helper.nf

dependencies:
  - name: datasets/loaders/vizgen_merscope
  - name: datasets/processors/crop_region

runners:
  - type: nextflow
    directives:
      label: [highcpu, highmem, hightime]
