name: nsclc_sc_zuani
namespace: datasets/workflows

argument_groups:

  - name: Caching settings
    arguments:
      - type: boolean
        name: --keep_files
        required: false
        description: Whether to remove the downloaded files after processing.
        default: false
  - name: Metadata
    arguments:
      - type: string
        name: --dataset_id
        description: "A unique identifier for the dataset"
        required: false
        default: "E-MTAB-13526" 
      - name: --dataset_name
        type: string
        description: Nicely formatted name.
        required: false
        default: "E-MTAB-13526" 
      - type: string
        name: --dataset_url
        description: Link to the original source of the dataset.
        required: false
        default: "https://www.ebi.ac.uk/biostudies/arrayexpress/studies/E-MTAB-13526" 
      - name: --dataset_reference
        type: string
        description: Bibtex reference of the paper in which the dataset was published.
        required: false
        default: "https://www.ebi.ac.uk/biostudies/arrayexpress/studies/E-MTAB-13526" 
      - name: --dataset_summary
        type: string
        description: Short description of the dataset.
        required: true
        default: "We performed single cell RNA sequencing (scRNA-seq) of NSCLC tumours and matched, adjacent, non-involved lung tissue from 24 patients. The data set is composed of approximately 900,000 cells from two different populations: CD235- (haematopoietic and non-haematopoietic cells depleted of erythrocytes), and CD45+ (all haematopoietic cells)." 
      - name: --dataset_description
        type: string
        description: Long description of the dataset.
        required: true
        default: "We performed single cell RNA sequencing (scRNA-seq) of NSCLC tumours and matched, adjacent, non-involved lung tissue from 24 patients. The data set is composed of approximately 900,000 cells from two different populations: CD235- (haematopoietic and non-haematopoietic cells depleted of erythrocytes), and CD45+ (all haematopoietic cells)." 
      - name: --dataset_organism
        type: string
        description: The organism of the sample in the dataset.
        required: false
        default: "human" 
  - name: Outputs
    arguments:
    - name: "--output"
      __merge__: /src/api/file_common_scrnaseq.yaml
      direction: output
      required: true
      default: "$id/dataset.h5ad"
    - name: "--output_meta"
      direction: "output"
      type: file
      description: "Dataset metadata"
      default: "$id/dataset_meta.yaml"

resources:
  - type: nextflow_script
    path: main.nf
    entrypoint: run_wf
  - path: /common/nextflow_helpers/helper.nf

dependencies:
  - name: datasets/loaders/nsclc_sc_zuani
#  - name: datasets/processors/subsample
#    repository: openproblems
  - name: datasets/normalization/log_cp
    repository: openproblems
  - name: datasets/processors/pca
    repository: openproblems
  - name: datasets/processors/hvg
    repository: openproblems
  - name: datasets/processors/knn
    repository: openproblems
  - name: h5ad/extract_uns_metadata
    repository: core

runners:
  - type: nextflow
    directives:
      label: [midcpu, midmem, hightime]
